---
- hosts: webservers
  become: true

  tasks:
    - name: Install httpd
      yum:
        name: "httpd"
        state: "present"

    - name: Installing dependencies
      yum:
        name:
          - php
          - php-xml
          - php-mbstring
          - ImageMagick-perl
        state: present

    - name: Start Apache Server
      service:
         name: "httpd"
         state: started
         enabled: True

    - name: Mediawiki Download and configure
      shell: |
         yum install wget
         mkdir /var/www/html
         cd /tmp/
         sudo rm -rf med*
         wget http://releases.wikimedia.org/mediawiki/1.24/mediawiki-1.24.1.tar.gz
         tar -xvf med*
         sudo rm -rf /var/www/html/*
         mv med*/* /var/www/html/
